feedback/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.feedbackView, name='feedback'),
    url(r'^send/$', views.sendView, name='send'),
    url(r'^a5d491060952aa8ad5fdee071be752de/$', views.commentsView, name='comments'),
    url(r'^06d4cd63bde972fc66a0aed41d2f5c51/(?P<commentId>[0-9]+)/$', views.commentView, name='comment'),
]

startline/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'startline.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^feedback/', include('feedback.urls', namespace='feedback')),
)

feedback/models.py
from django.db import models


class Comment(models.Model):
    author = models.CharField(max_length=200)
    subject = models.CharField(max_length=200)
    text = models.CharField(max_length=1000)
    date = models.DateTimeField('date published')

    def __str__(self):
        return self.subject

feedback/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.utils import timezone

from .models import Comment


def feedbackView(request):
    return render(request, 'feedback.html')


def sendView(request):
    author = request.POST['author']
    subject = request.POST['subject']
    text = request.POST['text']
    id = Comment.objects.count() + 1

    comment = Comment(id, author, subject, text, timezone.now())
    comment.save()

    return HttpResponseRedirect(reverse('index'))


def commentsView(request):
    return render(request, 'comments.html', {'comments': Comment.objects.all()})


def commentView(request, commentId):
    comment = get_object_or_404(Comment, pk=commentId)
    return render(request, 'comment.html', {'comment': comment})

startline/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext


def handler404(request):
    response = render_to_response('404.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 404
    return response


def handler500(request):
    response = render_to_response('500.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 500
    return response

feedback/templates/comment.html
<table>
    <tr>
        <td><label for="author">Автор</label></td>
        <td><input type="text" name="author" id="author" value="{{ comment.author }}"></td>
    </tr>
    <tr>
        <td><label>Тема</label></td>
        <td><input type="text" name="subject" id="subject" value="{{ comment.subject }}"></td>
    </tr>
    <tr>
        <td><label for="text">Сообщение</label></td>
        <td><textarea name="text" id="text" cols="50" rows="10">{{ comment.text }}</textarea></td>
    </tr>
</table>

feedback/templates/comments.html
<table>
    <tr>
        <td>Тема</td>
        <td>Время отправки</td>
    </tr>
    {% for comment in comments %}
    <tr>
        <td><a href=" {% url 'feedback:comment' comment.id %}">{{ comment.subject }}</a></td>
        <td>{{ comment.date }}</td>
    </tr>
    {% endfor %}
</table>

feedback/templates/feedback.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
</head>
<body>
    <div class="container">
        <img class="" src="/static/img/logo.png" style="width: 216px; height: 68px; margin-top: 5px; margin-bottom: 45px;">
        <div class="parent center-block" style="padding-top: 40px;">

        <div class="child-without-center">

            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            <form action="{% url 'feedback:send' %}" method="post">
            {% csrf_token %}
                <table>
                    <tr>
                        <td class="offset-right"><label for="author">Ваше имя</label></td>
                        <td><input type="text" name="author" id="author"></td>
                    </tr>
                    <tr></tr>
                    <tr>
                        <td class="offset-right"><label>Ваш телефон или e-mail</label></td>
                        <td><input type="text" name="subject" id="subject"></td>
                    </tr>
                    <tr>
                        <td><label for="text">Что Вас интересует?</label></td>
                        <td><textarea name="text" id="text" cols="50" rows="10"></textarea></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td rowspan="2" class="offset-right"><input type="submit" onclick='console.log("sdsds"); location.href="http://127.0.0.1:8000/"' value="Оставить заявку" /></td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
    </div>


    <footer class="footer">
      <div class="container">
          <ul class="nav navbar-nav">
             <li class="myfooter">
                   <strong>Startline IT | 2015</strong>
             </li>
              <li class="myfooter">
                  <strong></strong>
              </li>
          </ul>
           <ul class="nav navbar-nav navbar-right">
               <li class="myfooter">
                   <abbr title="Адрес"><span class="glyphicon glyphicon-home"></span></abbr> г. Саратов, ул. Октябрьская, 44
               </li>
               <li class="myfooter">
                   <abbr title="Телефон"><span class="glyphicon glyphicon-phone-alt"></span></abbr> +7(8452) 650-122
               </li>
          </ul>
      </div>
    </footer>
</body>
<script>

</script>
</html>

templates/css.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Startline IT</title>
    {% include 'css.html' %}
</head>
<body>
  <div class="container-fluid">
            <div class="parent center-block">
                <div class="child">
                    <img src="static/img/logo.png" style="width: 216px; height: 68px;">
                    <blockquote>
                      <p>Ваш пропуск в мир информационных технологий</p>
                    </blockquote>
                    <div class="feedback">
                      <a href="{% url 'feedback:feedback' %}">Свяжитесь с нами!</a>
                    </div>
                </div>
            </div>
            <div>

            </div>
      </div>

<footer class="footer">
  <div class="container">
      <ul class="nav navbar-nav">
         <li class="myfooter">
               <strong>Startline IT | 2015</strong>
         </li>
          <li class="myfooter">
              <strong></strong>
          </li>
      </ul>
       <ul class="nav navbar-nav navbar-right">
           <li class="myfooter">
               <abbr title="Адрес"><span class="glyphicon glyphicon-home"></span></abbr> г. Саратов, ул. Октябрьская, 44
           </li>
           <li class="myfooter">
               <abbr title="Телефон"><span class="glyphicon glyphicon-phone-alt"></span></abbr> +7(8452) 650-122
           </li>
      </ul>
  </div>
</footer>
</body>
</html>